comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_head: no     # default yes
  require_base: no 

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
